import type { AuthoredProject } from '../types.js';

export const babyNames: AuthoredProject = {
	slug: 'baby-names',
	tagline:
		'An AI-powered baby name finder that learns your taste: rate generated examples, then receive personalised suggestions that update as you narrow down.',
	blurb: 'An AI name finder that learns your taste through a rating loop.',
	description:
		'There is no local dataset; every name is generated by the Claude API. The flow runs across three screens. On Preferences, you set gender, thematic clusters (Mythology, Nature, Celestial and ten others), cultural origins (sixteen options), and a uniqueness slider from Commonplace to Unique. On Tasting, the app generates around twenty example names and presents them one at a time; you rate each like, neutral, or dislike using keyboard shortcuts. On Results, the app feeds the learned taste back to the model (liked patterns, disliked patterns, an exclusion list of everything already seen) and generates ten personalised names. Selecting which to keep and regenerating the rest is an iterative refine loop: the rest are excluded permanently so no name repeats. A server-side SvelteKit endpoint proxies Anthropic so the API key never reaches the browser; the original React prototype called Anthropic directly from the client.',
	kind: 'toy',
	contribution: { role: 'solo' },
	status: 'finished',
	track: 'product',
	progress: 'complete',
	highlights: [
		'No local dataset: all names generated on demand via the Claude API.',
		'Three-screen taste-learning loop: set preferences, rate generated examples, receive personalised results.',
		'Iterative refine: keep selected names, regenerate the rest with a growing exclusion list so no name repeats.',
		'Server-side Anthropic proxy keeps the API key off the client; the React prototype it was ported from called the API directly from the browser.',
		'Defensive LLM-output parsing: fence-stripping, bracket-slicing, shape validation, and descriptive errors for empty or malformed responses.'
	],
	relationships: [],
	tags: [{ label: 'Claude API', kind: 'ai' }]
};
